image: Visual Studio 2017
version: 0.4.{build}

before_build:
  - choco install codecov
  - nuget restore
build_script:
  - dotnet build PrimitiveBase.sln
test_script:
  - dotnet test /p:CollectCoverage=true /p:Include=[PBase]* /p:CoverletOutputFormat=opencover /p:CoverletOutput=../../
  - dir
after_test:
  - dir
  - codecov -f "coverage.opencover.xml" -t $CODECOV
