image: Visual Studio 2017
version: 0.4.{build}

configuration:
  - Debug
  - Release
before_build:
  - choco install codecov
  - nuget restore
build_script:
  - dotnet build PrimitiveBase.sln
test_script:
  - dotnet test /p:CollectCoverage=true /p:Include=[PBase]* /p:CoverletOutputFormat=opencover /p:CoverletOutput=../../
after_test:
  - codecov -f "coverage.opencover.xml" -t $CODECOV

deploy:
  provider: nuget
  api_key:
    secure: shxGZasNtag0zVi38/DH2ToxfrUDNzZSFIevIKemuVKDfCzmNm//UCWG1Ysi0i+2
  skip_symbols: false
  artifact: /.*/Release/\.nupkg

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'