# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "PrimitiveBase.sln"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:Configuration=$BUILD_CONFIG /p:Include=[PBase]* /p:CoverletOutputFormat=opencover /p:CoverletOutput=../../ --no-restore --no-build
      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
